# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('ballMessage_id', models.CharField(max_length=20, null=True)),
                ('ball_id', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ball_enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ball_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=50)),
                ('num', models.IntegerField(default=0)),
                ('message', models.CharField(max_length=100)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ball_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_ID', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=50)),
                ('current_time', models.DateTimeField(auto_now_add=True)),
                ('ball_object', models.CharField(max_length=50)),
                ('money', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=10)),
                ('ball_format', models.CharField(max_length=10)),
                ('num_people', models.IntegerField(default=0)),
                ('current_people', models.IntegerField(default=0)),
                ('introduction', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ball_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image', models.CharField(default='userImage/default_face.jpg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='zan_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
