# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-13 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ball_enroll',
            name='status',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
