# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colordic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColorName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.BooleanField(default=False)),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoProject1.Colordic')),
            ],
        ),
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
