# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject1', '0003_authorlist_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personpaiming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='Color',
        ),
        migrations.AlterField(
            model_name='book',
            name='BookName',
            field=models.CharField(help_text='hhaha', max_length=10),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
