# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject1', '0004_auto_20160615_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorList2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
        ),
    ]
